# Generated by Django 4.0.2 on 2022-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf_number',
            field=models.IntegerField(unique=True),
        ),
    ]
