# Generated by Django 4.0.2 on 2022-02-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
