# Generated by Django 4.0.2 on 2022-02-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
