# Generated by Django 4.0.2 on 2022-02-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
    ]
