# Generated by Django 4.0.2 on 2022-02-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
