# Generated by Django 4.0.2 on 2022-02-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
